version: "3.3"
services:
  db:
    build: db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=password
    image: localhost:8081/docker-local/proj_mysql
  backend:
    build: backend
    restart: always
    
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
    image: localhost:8081/docker-local/proj_backend
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
    image: localhost:8081/docker-local/proj_proxy
volumes:
  db-data:

networks:
  backnet:
  frontnet:
