---
# tasks file for flask_setup


  - name: Update and upgrade apt packages
    become: true
    apt:
      update_cache: yes
      upgrade: 'yes'
    when: ansible_os_family == 'Debian'

  
  - name: upgrade all packages
    yum: 
      name: "*"
      state: latest
    when: ansible_os_family == 'RedHat'
 



  - name: Install requirements
    pip:
      requirements: /home/{{ansible_ssh_user }}/code/requirements.txt
     




  - name: Update and upgrade apt packages
    become: true
    apt:
      update_cache: yes
      upgrade: 'yes'
    when: ansible_os_family == 'Debian'

  
  - name: upgrade all packages
    yum: 
      name: "*"
      state: latest
    when: ansible_os_family == 'RedHat'







  - name : rmeoving default nginx sites
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    become : yes

  - name: copy sites
    copy:
      src: supervisor.j2
      dest: /etc/nginx/sites-available/example.com
    become: yes

  - name: ls
    file:
       src : /etc/nginx/sites-available/example.com
       dest: /etc/nginx/sites-enabled/example.com
       state: link

 

  - name: RestartNginx
    service: 
      name: nginx
      state: restarted
 


  - name :  running gunicorn3
    shell :  cd code && gunicorn3 --workers="{{ (ansible_processor_cores*2+1)|int }}"  app:app --daemon
    become: yes
