---
# tasks file for docker
      
 





    - name: Create and start services
      #docker-compose working in docker-playground , but now working in EC2 instance and my computer docker,docker-py are making issues.
      # docker_compose:
      #   project_src: "{{ role_path }}/files"
      shell: sudo docker-compose -f "{{ role_path }}"/files/docker-compose.yml  up --build -d
      register: output

    - name: debugging docker compose 
      debug:
        var: output