---
- name: pauser
  pause: seconds=2

- name: restart apache
  service: name={{ nagios_apache_service }} state=restarted

- name: restart nagios
  become: true
  service: name=nagios state=restarted

- name: restart nrpe
  become: true
  service: name={{ nrpe_service_name }} state=restarted
